/* The following code was generated by JFlex 1.6.1 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>gachaneitor.jflex</tt>
 */
class gachaneitor {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\1\1\65\1\65\1\2\22\0\1\3\1\0\1\13"+
    "\5\0\1\61\1\62\2\0\1\60\3\0\1\6\11\10\1\37\1\36"+
    "\5\0\1\27\1\12\1\25\1\55\1\15\1\12\1\54\1\12\1\24"+
    "\1\12\1\26\1\41\1\14\1\16\1\43\1\40\1\12\1\52\1\44"+
    "\1\42\1\17\4\12\1\63\4\5\1\7\1\5\1\33\1\12\1\31"+
    "\1\57\1\21\1\12\1\56\1\12\1\30\1\12\1\32\1\46\1\20"+
    "\1\22\1\50\1\45\1\12\1\53\1\51\1\47\1\23\4\12\1\64"+
    "\1\34\1\0\1\35\7\0\1\65\u05da\0\12\11\206\0\12\11\306\0"+
    "\12\11\u019c\0\12\11\166\0\12\11\166\0\12\11\166\0\12\11\166\0"+
    "\12\11\166\0\12\11\166\0\12\11\166\0\12\11\166\0\12\11\166\0"+
    "\12\11\140\0\12\11\166\0\12\11\106\0\12\11\u0116\0\12\11\106\0"+
    "\12\11\u0746\0\12\11\46\0\12\11\u012c\0\12\11\200\0\12\11\246\0"+
    "\12\11\6\0\12\11\266\0\12\11\126\0\12\11\206\0\12\11\6\0"+
    "\12\11\u03ce\0\1\65\1\65\u85f6\0\12\11\u02a6\0\12\11\46\0\12\11"+
    "\306\0\12\11\26\0\12\11\126\0\12\11\u0196\0\12\11\u5316\0\12\11"+
    "\u0586\0\12\11\u0bbc\0\12\11\200\0\12\11\74\0\12\11\220\0\12\11"+
    "\u0116\0\12\11\u01d6\0\12\11\u0176\0\12\11\146\0\12\11\u0216\0\12\11"+
    "\u5176\0\12\11\346\0\12\11\u6c74\0\62\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u280f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\1\10\3\1\5"+
    "\1\6\1\7\1\10\10\3\1\11\1\12\1\13\1\14"+
    "\1\0\24\3\1\15\30\3\1\16\10\3\1\17\3\3"+
    "\1\20\1\3\1\17\16\3\1\21\1\22\2\3\1\23"+
    "\1\22\14\3\1\24\1\3\1\25\17\3\1\26\10\3"+
    "\1\27\6\3\1\30\1\31\1\3\1\32\3\3\1\33";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\66\0\154\0\242\0\330\0\u010e\0\u0144"+
    "\0\u017a\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\66"+
    "\0\66\0\66\0\66\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc"+
    "\0\u0402\0\u0438\0\u046e\0\66\0\66\0\66\0\66\0\u04a4"+
    "\0\u04da\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e\0\u0654"+
    "\0\u068a\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798\0\u07ce\0\u0804"+
    "\0\u083a\0\u0870\0\u08a6\0\u08dc\0\66\0\u0912\0\u0948\0\u097e"+
    "\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e"+
    "\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde"+
    "\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec\0\242\0\u0e22\0\u0e58"+
    "\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\u0f66\0\u0f9c\0\u0fd2\0\u1008"+
    "\0\u103e\0\u1074\0\242\0\u10aa\0\u10e0\0\u1116\0\u114c\0\u1182"+
    "\0\u11b8\0\u11ee\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12fc\0\u1332"+
    "\0\u1368\0\u139e\0\u13d4\0\242\0\u140a\0\u1440\0\u1476\0\242"+
    "\0\u14ac\0\u14e2\0\u1518\0\u154e\0\u1584\0\u15ba\0\u15f0\0\u1626"+
    "\0\u165c\0\u1692\0\u16c8\0\u16fe\0\u1734\0\242\0\u176a\0\242"+
    "\0\u17a0\0\u17d6\0\u180c\0\u1842\0\u1878\0\u18ae\0\u18e4\0\u191a"+
    "\0\u1950\0\u1986\0\u19bc\0\u19f2\0\u1a28\0\u1a5e\0\u1a94\0\242"+
    "\0\u1aca\0\u1b00\0\u1b36\0\u1b6c\0\u1ba2\0\u1bd8\0\u1c0e\0\u1c44"+
    "\0\242\0\u1c7a\0\u1cb0\0\u1ce6\0\u1d1c\0\u1d52\0\u1d88\0\242"+
    "\0\242\0\u1dbe\0\242\0\u1df4\0\u1e2a\0\u1e60\0\242";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\3\1\5\1\2\1\5\1\6"+
    "\1\2\1\5\1\7\1\10\1\5\1\11\1\5\1\12"+
    "\1\5\1\13\1\5\1\14\1\15\2\5\1\16\1\17"+
    "\2\5\1\20\1\21\1\22\1\23\1\24\1\5\1\25"+
    "\1\5\1\26\1\27\1\5\1\30\1\5\1\31\1\32"+
    "\1\33\4\5\1\34\1\35\1\36\2\5\1\37\67\0"+
    "\1\3\72\0\3\5\1\0\1\5\1\0\20\5\4\0"+
    "\20\5\3\0\2\5\7\0\1\6\1\0\2\6\66\0"+
    "\1\40\1\0\20\40\4\0\20\40\3\0\2\40\7\0"+
    "\3\5\1\0\1\5\1\0\1\5\1\41\16\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\10\5\1\42\7\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\5\5\1\43\12\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\14\5\1\44\3\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\2\5\1\45\15\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\3\5\1\46\14\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\6\5\1\47\11\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\10\5\1\50\7\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\13\5\1\51\4\5\4\0"+
    "\1\5\1\52\10\5\1\53\5\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\10\5\1\54\7\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\13\5\1\55\4\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\17\5\1\56\4\0\6\5"+
    "\1\57\4\5\1\60\4\5\3\0\2\5\7\0\3\5"+
    "\1\0\1\5\1\0\14\5\1\61\3\5\4\0\20\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\17\5"+
    "\1\62\4\0\20\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\1\5\1\63\16\5\4\0\20\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\5\5\1\64"+
    "\12\5\4\0\20\5\3\0\2\5\4\0\1\40\3\0"+
    "\1\40\2\0\1\40\1\65\20\40\4\0\20\40\3\0"+
    "\2\40\7\0\3\5\1\0\1\5\1\0\2\5\1\66"+
    "\15\5\4\0\20\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\11\5\1\67\6\5\4\0\20\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\6\5\1\70"+
    "\11\5\4\0\20\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\15\5\1\71\2\5\4\0\20\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\20\5\4\0"+
    "\2\5\1\72\11\5\1\73\3\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\1\74\17\5\4\0\20\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\20\5"+
    "\4\0\7\5\1\75\6\5\1\76\1\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\4\5\1\77\13\5"+
    "\4\0\20\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\20\5\4\0\4\5\1\100\13\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\13\5\1\101\4\5"+
    "\4\0\20\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\20\5\4\0\3\5\1\102\14\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\1\5\1\103\16\5"+
    "\4\0\1\104\17\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\11\5\1\105\6\5\4\0\20\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\20\5\4\0"+
    "\11\5\1\106\6\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\17\5\1\107\4\0\20\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\20\5\4\0\10\5"+
    "\1\110\7\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\5\5\1\111\12\5\4\0\5\5\1\112\12\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\15\5"+
    "\1\113\2\5\4\0\20\5\3\0\2\5\7\0\3\5"+
    "\1\0\1\5\1\0\13\5\1\114\4\5\4\0\20\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\17\5"+
    "\1\115\4\0\20\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\3\5\1\116\14\5\4\0\20\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\12\5\1\117"+
    "\5\5\4\0\20\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\7\5\1\116\10\5\4\0\20\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\16\5\1\120"+
    "\1\5\4\0\20\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\20\5\4\0\12\5\1\121\5\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\20\5\4\0"+
    "\12\5\1\122\5\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\1\5\1\123\16\5\4\0\20\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\20\5\4\0"+
    "\13\5\1\124\4\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\20\5\4\0\13\5\1\125\4\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\5\5\1\126"+
    "\12\5\4\0\20\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\20\5\4\0\3\5\1\127\14\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\20\5\4\0"+
    "\2\5\1\130\15\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\20\5\4\0\14\5\1\131\3\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\1\132\17\5"+
    "\4\0\20\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\20\5\4\0\3\5\1\133\14\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\13\5\1\134\4\5"+
    "\4\0\20\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\20\5\4\0\10\5\1\135\7\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\20\5\4\0\7\5"+
    "\1\136\10\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\20\5\4\0\16\5\1\137\1\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\4\5\1\140\13\5"+
    "\4\0\20\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\20\5\4\0\10\5\1\133\7\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\17\5\1\141\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\1\5\1\142\16\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\6\5\1\143"+
    "\11\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\2\5\1\144\15\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\6\5\1\145\11\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\3\5\1\146\14\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\1\5\1\147\16\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\2\5\1\150\15\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\10\5\1\151"+
    "\7\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\5\5\1\152\12\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\6\5\1\153\11\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\4\5\1\154\13\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\3\5\1\155"+
    "\14\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\12\5\1\156\5\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\1\157\17\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\20\5"+
    "\4\0\12\5\1\160\5\5\3\0\2\5\7\0\3\5"+
    "\1\0\1\5\1\0\20\5\4\0\11\5\1\154\6\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\20\5"+
    "\4\0\10\5\1\161\7\5\3\0\2\5\7\0\3\5"+
    "\1\0\1\5\1\0\20\5\4\0\13\5\1\162\4\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\20\5"+
    "\4\0\5\5\1\163\12\5\3\0\2\5\7\0\3\5"+
    "\1\0\1\5\1\0\20\5\4\0\13\5\1\160\4\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\10\5"+
    "\1\164\7\5\4\0\20\5\3\0\2\5\7\0\3\5"+
    "\1\0\1\5\1\0\14\5\1\165\3\5\4\0\20\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\13\5"+
    "\1\166\4\5\4\0\20\5\3\0\2\5\7\0\3\5"+
    "\1\0\1\5\1\0\17\5\1\167\4\0\20\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\20\5\4\0"+
    "\15\5\1\170\2\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\20\5\4\0\15\5\1\171\2\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\20\5\4\0"+
    "\4\5\1\172\13\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\20\5\4\0\17\5\1\173\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\20\5\4\0\17\5"+
    "\1\174\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\11\5\1\175\6\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\4\5\1\176"+
    "\13\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\13\5\1\177\4\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\3\5\1\200"+
    "\14\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\11\5\1\176\6\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\17\5\1\201\4\0\20\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\20\5"+
    "\4\0\10\5\1\200\7\5\3\0\2\5\7\0\3\5"+
    "\1\0\1\5\1\0\20\5\4\0\20\5\3\0\1\202"+
    "\1\5\7\0\3\5\1\0\1\5\1\0\20\5\4\0"+
    "\20\5\3\0\1\5\1\203\7\0\3\5\1\0\1\5"+
    "\1\0\1\204\17\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\4\5\1\205\13\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\3\5\1\206\14\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\10\5\1\207\7\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\13\5\1\210\4\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\7\5\1\211\10\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\14\5\1\212\3\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\17\5\1\213\4\0\20\5"+
    "\3\0\2\5\7\0\3\5\1\0\1\5\1\0\1\214"+
    "\17\5\4\0\20\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\4\5\1\215\13\5\4\0\20\5\3\0"+
    "\2\5\7\0\3\5\1\0\1\5\1\0\13\5\1\216"+
    "\4\5\4\0\20\5\3\0\2\5\7\0\3\5\1\0"+
    "\1\5\1\0\17\5\1\217\4\0\20\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\1\5\1\220\16\5"+
    "\4\0\20\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\5\5\1\220\12\5\4\0\20\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\11\5\1\221\6\5"+
    "\4\0\20\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\1\5\1\222\16\5\4\0\20\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\20\5\4\0\1\5"+
    "\1\223\16\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\15\5\1\224\2\5\4\0\20\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\5\5\1\225\12\5"+
    "\4\0\20\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\20\5\4\0\6\5\1\226\11\5\3\0\2\5"+
    "\7\0\3\5\1\0\1\5\1\0\13\5\1\227\4\5"+
    "\4\0\20\5\3\0\2\5\7\0\3\5\1\0\1\5"+
    "\1\0\17\5\1\230\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\12\5\1\231"+
    "\5\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\13\5\1\231\4\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\10\5\1\232\7\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\2\5\1\233\15\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\1\5\1\234\16\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\14\5\1\235\3\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\6\5\1\236\11\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\5\5\1\237\12\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\12\5\1\240"+
    "\5\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\13\5\1\240\4\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\12\5\1\241"+
    "\5\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\2\5\1\242\15\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\4\5\1\243"+
    "\13\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\13\5\1\241\4\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\7\5\1\244"+
    "\10\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\11\5\1\243\6\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\1\5\1\245\16\5\4\0"+
    "\20\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\5\5\1\246\12\5\4\0\20\5\3\0\2\5\7\0"+
    "\3\5\1\0\1\5\1\0\20\5\4\0\4\5\1\247"+
    "\13\5\3\0\2\5\7\0\3\5\1\0\1\5\1\0"+
    "\20\5\4\0\11\5\1\247\6\5\3\0\2\5\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7830];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\14\1\4\11\10\1\4\11\1\0\24\1"+
    "\1\11\162\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  gachaneitor(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 384) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Token erroneo");
            }
          case 28: break;
          case 2: 
            { /* No hacer nada */
            }
          case 29: break;
          case 3: 
            { System.out.println("Token id");
            }
          case 30: break;
          case 4: 
            { System.out.println("Token entero");
            }
          case 31: break;
          case 5: 
            { System.out.println("Token {");
            }
          case 32: break;
          case 6: 
            { System.out.println("Token }");
            }
          case 33: break;
          case 7: 
            { System.out.println("Token ;");
            }
          case 34: break;
          case 8: 
            { System.out.println("Token :");
            }
          case 35: break;
          case 9: 
            { System.out.println("Token ,");
            }
          case 36: break;
          case 10: 
            { System.out.println("Token (");
            }
          case 37: break;
          case 11: 
            { System.out.println("Token )");
            }
          case 38: break;
          case 12: 
            { System.out.print(yytext());
            }
          case 39: break;
          case 13: 
            { System.out.println("Token cadena");
            }
          case 40: break;
          case 14: 
            { System.out.println("Token menu");
            }
          case 41: break;
          case 15: 
            { System.out.println("Token paso");
            }
          case 42: break;
          case 16: 
            { System.out.println("Token tipo");
            }
          case 43: break;
          case 17: 
            { System.out.println("Token pasos");
            }
          case 44: break;
          case 18: 
            { System.out.println("Token plato");
            }
          case 45: break;
          case 19: 
            { System.out.println("Token sacar");
            }
          case 46: break;
          case 20: 
            { System.out.println("Token platos");
            }
          case 47: break;
          case 21: 
            { System.out.println("Token tiempo");
            }
          case 48: break;
          case 22: 
            { System.out.println("Token nickname");
            }
          case 49: break;
          case 23: 
            { System.out.println("Token realizar");
            }
          case 50: break;
          case 24: 
            { System.out.println("Token programar");
            }
          case 51: break;
          case 25: 
            { System.out.println("Token introducir");
            }
          case 52: break;
          case 26: 
            { System.out.println("Token comensales");
            }
          case 53: break;
          case 27: 
            { System.out.println("Token ingredientes");
            }
          case 54: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java gachaneitor [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        gachaneitor scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new gachaneitor(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
