
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 18 02:11:06 CET 2020
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Jan 18 02:11:06 CET 2020
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\052\000\002\002\003\000\002\002\004\000\002\003" +
    "\003\000\002\003\004\000\002\004\015\000\002\005\005" +
    "\000\002\015\002\000\002\016\002\000\002\017\002\000" +
    "\002\006\006\000\002\007\003\000\002\007\004\000\002" +
    "\011\006\000\002\021\006\000\002\021\002\000\002\022" +
    "\003\000\002\022\004\000\002\023\010\000\002\010\004" +
    "\000\002\010\005\000\002\012\013\000\002\013\005\000" +
    "\002\014\005\000\002\020\016\000\002\020\006\000\002" +
    "\020\012\000\002\024\010\000\002\025\006\000\002\025" +
    "\007\000\002\026\006\000\002\026\004\000\002\026\006" +
    "\000\002\030\004\000\002\030\002\000\002\031\007\000" +
    "\002\032\003\000\002\032\004\000\002\033\017\000\002" +
    "\034\007\000\002\035\003\000\002\035\005\000\002\036" +
    "\011" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\203\000\004\023\006\001\002\000\006\002\uffff\023" +
    "\006\001\002\000\004\002\204\001\002\000\004\004\010" +
    "\001\002\000\004\002\001\001\002\000\004\017\011\001" +
    "\002\000\004\005\012\001\002\000\004\013\013\001\002" +
    "\000\004\022\014\001\002\000\004\004\202\001\002\000" +
    "\004\024\017\001\002\000\006\033\ufff3\035\032\001\002" +
    "\000\004\013\020\001\002\000\004\004\022\001\002\000" +
    "\006\004\022\014\ufff7\001\002\000\004\017\025\001\002" +
    "\000\004\014\024\001\002\000\006\033\ufff8\035\ufff8\001" +
    "\002\000\004\005\026\001\002\000\004\015\027\001\002" +
    "\000\006\004\ufff5\014\ufff5\001\002\000\004\014\ufff6\001" +
    "\002\000\004\033\ufffb\001\002\000\004\013\033\001\002" +
    "\000\004\004\035\001\002\000\004\014\045\001\002\000" +
    "\004\017\040\001\002\000\006\004\035\014\ufff2\001\002" +
    "\000\004\014\ufff1\001\002\000\004\012\041\001\002\000" +
    "\004\010\042\001\002\000\004\005\043\001\002\000\004" +
    "\015\044\001\002\000\006\004\ufff0\014\ufff0\001\002\000" +
    "\006\030\ufff4\033\ufff4\001\002\000\004\033\050\001\002" +
    "\000\004\014\201\001\002\000\004\004\054\001\002\000" +
    "\006\014\ufffa\033\ufffa\001\002\000\006\014\uffef\033\050" +
    "\001\002\000\004\014\uffee\001\002\000\004\013\055\001" +
    "\002\000\004\031\056\001\002\000\004\007\177\001\002" +
    "\000\004\027\061\001\002\000\006\036\064\037\065\001" +
    "\002\000\004\012\062\001\002\000\004\015\063\001\002" +
    "\000\006\036\uffeb\037\uffeb\001\002\000\004\012\164\001" +
    "\002\000\004\012\161\001\002\000\006\030\ufff3\035\032" +
    "\001\002\000\004\030\071\001\002\000\004\014\160\001" +
    "\002\000\004\013\072\001\002\000\006\026\uffe0\034\073" +
    "\001\002\000\004\020\154\001\002\000\014\014\uffe0\025" +
    "\uffe0\026\uffe0\032\uffe0\034\073\001\002\000\004\026\ufffb" +
    "\001\002\000\004\026\101\001\002\000\004\014\152\001" +
    "\002\000\004\025\140\001\002\000\004\020\127\001\002" +
    "\000\010\026\101\032\uffe0\034\073\001\002\000\004\025" +
    "\uffe3\001\002\000\004\032\106\001\002\000\010\025\uffe0" +
    "\026\101\034\073\001\002\000\004\020\111\001\002\000" +
    "\012\025\uffde\026\uffde\032\106\034\uffde\001\002\000\010" +
    "\025\uffdd\026\uffdd\034\uffdd\001\002\000\004\005\112\001" +
    "\002\000\004\016\113\001\002\000\004\012\114\001\002" +
    "\000\004\016\115\001\002\000\004\012\116\001\002\000" +
    "\004\016\117\001\002\000\004\012\120\001\002\000\004" +
    "\016\121\001\002\000\004\006\122\001\002\000\004\021" +
    "\123\001\002\000\004\015\124\001\002\000\012\025\uffdc" +
    "\026\uffdc\032\uffdc\034\uffdc\001\002\000\004\025\uffe4\001" +
    "\002\000\004\025\uffe2\001\002\000\006\004\132\012\130" +
    "\001\002\000\004\010\135\001\002\000\004\021\133\001" +
    "\002\000\004\021\uffda\001\002\000\004\015\134\001\002" +
    "\000\010\026\uffdb\032\uffdb\034\uffdb\001\002\000\004\004" +
    "\136\001\002\000\004\021\uffd9\001\002\000\010\014\uffe0" +
    "\026\uffe0\034\073\001\002\000\004\020\141\001\002\000" +
    "\004\005\142\001\002\000\004\016\143\001\002\000\004" +
    "\004\144\001\002\000\004\021\145\001\002\000\004\015" +
    "\146\001\002\000\010\014\uffd8\026\uffd8\034\uffd8\001\002" +
    "\000\006\014\ufff9\026\ufff9\001\002\000\006\014\uffe6\026" +
    "\101\001\002\000\004\014\uffe5\001\002\000\004\014\uffe7" +
    "\001\002\000\012\014\uffe1\025\uffe1\026\uffe1\032\uffe1\001" +
    "\002\000\004\005\155\001\002\000\004\021\156\001\002" +
    "\000\004\015\157\001\002\000\014\014\uffdf\025\uffdf\026" +
    "\uffdf\032\uffdf\034\uffdf\001\002\000\006\014\uffed\033\uffed" +
    "\001\002\000\004\011\162\001\002\000\004\015\163\001" +
    "\002\000\006\030\uffe9\035\uffe9\001\002\000\004\011\165" +
    "\001\002\000\004\015\166\001\002\000\004\040\167\001" +
    "\002\000\004\012\170\001\002\000\004\011\171\001\002" +
    "\000\004\015\172\001\002\000\010\030\uffe8\035\uffe8\037" +
    "\173\001\002\000\004\012\174\001\002\000\004\011\175" +
    "\001\002\000\004\015\176\001\002\000\006\030\uffea\035" +
    "\uffea\001\002\000\004\015\200\001\002\000\004\027\uffec" +
    "\001\002\000\006\002\ufffd\023\ufffd\001\002\000\004\015" +
    "\203\001\002\000\004\024\ufffc\001\002\000\004\002\000" +
    "\001\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\203\000\010\002\004\003\006\004\003\001\001\000" +
    "\006\003\204\004\003\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\014\001\001\000\002" +
    "\001\001\000\004\006\015\001\001\000\004\021\030\001" +
    "\001\000\002\001\001\000\006\007\022\011\020\001\001" +
    "\000\006\007\027\011\020\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\015" +
    "\045\001\001\000\002\001\001\000\006\022\033\023\035" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\022" +
    "\036\023\035\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\010\046\012\050" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\016" +
    "\051\001\001\000\006\010\052\012\050\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\056\001\001\000" +
    "\002\001\001\000\004\014\057\001\001\000\004\020\065" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\021\066" +
    "\001\001\000\004\024\067\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\030\074\031\073\001\001\000\002" +
    "\001\001\000\006\030\152\031\073\001\001\000\004\015" +
    "\075\001\001\000\010\025\076\026\077\034\101\001\001" +
    "\000\002\001\001\000\004\036\136\001\001\000\002\001" +
    "\001\000\012\026\102\030\103\031\073\034\101\001\001" +
    "\000\002\001\001\000\006\032\104\033\106\001\001\000" +
    "\012\026\124\030\125\031\073\034\101\001\001\000\002" +
    "\001\001\000\006\032\107\033\106\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\035\130\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\030\146\031\073\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\017" +
    "\147\001\001\000\010\025\150\026\077\034\101\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	/*private LinkedList <String[]> outputs = new LinkedList<String[]>();
	private LinkedList <String> languages = new LinkedList<String>();
	private LinkedList <String> automatons = new LinkedList<String>();
	private LinkedList <String[]> states = new LinkedList<String[]>();
	private LinkedList <String[]> transitions = new LinkedList<String[]>();
	private String initial;
	private PrintWriter writer = null;*/

	public static void main(String args[]) throws Exception {
		File fichero=new File(args[0]);
		FileReader entrada =new FileReader(fichero);
		try{
			new parser(new scanner(entrada)).parse();
	   		System.out.println("Analisis CORRECTO");
		}
		catch ( Exception e) {
			System.out.println("Analisis INCORRECTO");
		}
 	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // SACAR ::= sacar izqParent cadena coma id drchParent pcoma 
            {
              PasoSacar RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
	((ArrayList<Ingrediente>) (((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-((Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value)-12)).value)).add(new Ingrediente(id, nom.substring(1,nom.length()-2), 1, EnumMedida.UDS));
	PasoSacar sacar = new PasoSacar(nom.substring(1,nom.length()-2));
	RESULT=sacar;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SACAR",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // INTRODUCIRARGS ::= numero medidaIngrediente id 
            {
              PasoIntroducir RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int medleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int medright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String med = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	PasoIntroducir introducir = new PasoIntroducir(id, num, EnumMedida.valueOf(med));
	RESULT=introducir;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("INTRODUCIRARGS",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // INTRODUCIRARGS ::= id 
            {
              PasoIntroducir RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	/*PasoIntroducir introducir = new PasoIntroducir(id);
	RESULT=introducir;*/

              CUP$parser$result = parser.getSymbolFactory().newSymbol("INTRODUCIRARGS",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // INTRODUCIR ::= introducir izqParent INTRODUCIRARGS drchParent pcoma 
            {
              PasoIntroducir RESULT =null;
		int intrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int intrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		PasoIntroducir intr = (PasoIntroducir)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
	RESULT=intr;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("INTRODUCIR",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // PASOMAQUINA ::= programar izqParent cadena coma numero coma numero coma numero coma invertir drchParent pcoma 
            {
              PasoMaquina RESULT =null;
		int desleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).left;
		int desright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).right;
		String des = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-10)).value;
		int velleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int velright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		Integer vel = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		int temleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int temright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Integer tem = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int tieleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int tieright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Integer tie = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int invleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int invright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String inv = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
	PasoMaquina paso = new PasoMaquina(des, vel, tem, tie, inv.equals("Si"));
	RESULT=paso;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PASOMAQUINA",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // PASOSMAQUINAS ::= PASOMAQUINA PASOSMAQUINAS 
            {
              ArrayList<Paso> RESULT =null;
		int pasmaqleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pasmaqright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		PasoMaquina pasmaq = (PasoMaquina)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int vpasleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vpasright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Paso> vpas = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	vpas.add(pasmaq);
	RESULT=vpas;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PASOSMAQUINAS",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // PASOSMAQUINAS ::= PASOMAQUINA 
            {
              ArrayList<Paso> RESULT =null;
		int pasmaqleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pasmaqright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		PasoMaquina pasmaq = (PasoMaquina)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	ArrayList<Paso> vpasos = new ArrayList<Paso>();
	vpasos.add(pasmaq);
	RESULT=vpasos;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PASOSMAQUINAS",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // PASOTEXTUAL ::= realizar izqParent cadena drchParent pcoma 
            {
              Paso RESULT =null;
		int desleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int desright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String des = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
	Paso paso = new Paso(des);
	RESULT=paso;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PASOTEXTUAL",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // PASOSTEXTUALES ::= 
            {
              ArrayList<Paso> RESULT =null;
		
	RESULT=new ArrayList<Paso>();

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PASOSTEXTUALES",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // PASOSTEXTUALES ::= PASOTEXTUAL PASOSTEXTUALES 
            {
              ArrayList<Paso> RESULT =null;
		int pastexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pastexright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Paso pastex = (Paso)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int vpastexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vpastexright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Paso> vpastex = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	vpastex.add(pastex);
	RESULT=vpastex;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PASOSTEXTUALES",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // PASOS ::= INTRODUCIR PASOSTEXTUALES PASOSMAQUINAS PASOSTEXTUALES 
            {
              ArrayList<Paso> RESULT =null;
		int intrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int intrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		PasoIntroducir intr = (PasoIntroducir)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int vpastexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vpastexright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<Paso> vpastex = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int vpasmaqleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vpasmaqright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Paso> vpasmaq = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int vpastex2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vpastex2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Paso> vpastex2 = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	ArrayList<Paso> vpasos = new ArrayList<Paso>();
	vpasos.addAll(vpastex);
	vpasos.add(intr);
	vpasos.addAll(vpastex2);
	vpasos.addAll(vpasmaq);
	RESULT=vpasos;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PASOS",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // PASOS ::= INTRODUCIR PASOS 
            {
              ArrayList<Paso> RESULT =null;
		int intrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int intrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		PasoIntroducir intr = (PasoIntroducir)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int vpasleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vpasright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Paso> vpas = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	vpas.add(intr);
	RESULT=vpas;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PASOS",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // PASOS ::= INTRODUCIR PASOSTEXTUALES PASOSMAQUINAS PASOS 
            {
              ArrayList<Paso> RESULT =null;
		int intrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int intrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		PasoIntroducir intr = (PasoIntroducir)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int vpastexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vpastexright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<Paso> vpastex = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int vpasmaqleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vpasmaqright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Paso> vpasmaq = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int vpasleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vpasright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Paso> vpas = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	vpas.addAll(vpastex);
	vpas.add(intr);
	vpas.addAll(vpasmaq);
	RESULT=vpas;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PASOS",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // LISTAPASOS ::= PASOS SACAR PASOSTEXTUALES N3 LISTAPASOS 
            {
              ArrayList<Paso> RESULT =null;
		int vpasleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int vpasright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		ArrayList<Paso> vpas = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int sacleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int sacright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		PasoSacar sac = (PasoSacar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int vpastexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vpastexright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<Paso> vpastex = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int vpasfinleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vpasfinright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Paso> vpasfin = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	vpasfin.addAll(vpastex);
	vpasfin.add(sac);
	vpasfin.addAll(vpas);
	RESULT=vpasfin;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTAPASOS",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // LISTAPASOS ::= PASOS SACAR PASOSTEXTUALES N3 
            {
              ArrayList<Paso> RESULT =null;
		int vpasleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int vpasright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<Paso> vpas = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sacleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int sacright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		PasoSacar sac = (PasoSacar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int vpastexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vpastexright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Paso> vpastex = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	ArrayList<Paso> vpasos = new ArrayList<Paso>();
	vpasos.addAll(vpastex);
	vpasos.add(sac);
	vpasos.addAll(vpas);
	RESULT=vpas;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTAPASOS",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // SECCIONPASOS ::= pasos izqLlave PASOSTEXTUALES NINIT LISTAPASOS drchLlave 
            {
              ArrayList<Paso> RESULT =null;
		int vpastexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int vpastexright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<Paso> vpastex = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int vpasleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vpasright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Paso> vpas = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	vpas.addAll(vpastex);
	RESULT=vpas;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SECCIONPASOS",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // TIEMPO ::= tCocinado numero medidaTiempo pcoma tPreparacion numero medidaTiempo pcoma 
            {
              Tiempos RESULT =null;
		int tcocleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int tcocright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Integer tcoc = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int mcocleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int mcocright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String mcoc = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int tpreleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tpreright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer tpre = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int mpreleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int mpreright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String mpre = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	Tiempos tiempos = new Tiempos(tcoc, EnumTiempo.valueOf(mcoc), tpre, EnumTiempo.valueOf(mpre), 0, EnumTiempo.valueOf("MIN"));
	RESULT=tiempos;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIEMPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // TIEMPO ::= tTotal numero medidaTiempo pcoma 
            {
              Tiempos RESULT =null;
		int ttotleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int ttotright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer ttot = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int mtotleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int mtotright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String mtot = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	Tiempos tiempos = new Tiempos(0, EnumTiempo.valueOf("MIN"), 0, EnumTiempo.valueOf("MIN"), ttot, EnumTiempo.valueOf(mtot));
	RESULT=tiempos;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIEMPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // TIEMPO ::= tCocinado numero medidaTiempo pcoma tPreparacion numero medidaTiempo pcoma tTotal numero medidaTiempo pcoma 
            {
              Tiempos RESULT =null;
		int tcocleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).left;
		int tcocright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).right;
		Integer tcoc = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-10)).value;
		int mcocleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left;
		int mcocright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).right;
		String mcoc = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;
		int tpreleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int tpreright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Integer tpre = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int mpreleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int mpreright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String mpre = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int ttotleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int ttotright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer ttot = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int mtotleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int mtotright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String mtot = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	Tiempos tiempos = new Tiempos(tcoc, EnumTiempo.valueOf(mcoc), tpre, EnumTiempo.valueOf(mpre), ttot, EnumTiempo.valueOf(mtot));
	RESULT=tiempos;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIEMPO",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // COMENSALES ::= comensales numero pcoma 
            {
              Integer RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	RESULT=num;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMENSALES",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // TIPO ::= tipo nombreTipo pcoma 
            {
              EnumTipo RESULT =null;
		int tipleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tipright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String tip = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	RESULT=EnumTipo.valueOf(tip);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TIPO",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // RECETA ::= plato id izqLlave TIPO COMENSALES TIEMPO SECCIONINGREDIENTES SECCIONPASOS drchLlave 
            {
              Plato RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int tipleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tipright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		EnumTipo tip = (EnumTipo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int comleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int comright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Integer com = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int tieleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tieright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Tiempos tie = (Tiempos)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int vingleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vingright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<Ingrediente> ving = (ArrayList<Ingrediente>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int vpasleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vpasright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Paso> vpas = (ArrayList<Paso>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	Plato plato = new Plato(id,"");
	ArrayList<Plato> vplatos = ((ArrayList<Plato>) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-((Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value)-11)).value);
	for(Plato p : vplatos) {
		if(id.equals(p.getID())) {
			System.out.println("Nuevo plato");
			plato.setNombre(p.getNombre());
			plato.setTipo(tip);
			plato.setComensales(com);
			plato.setTiempos(tie);
			plato.setIngredientes(ving);
			plato.setPasos(vpas);
		}


//Control de que no hay igual


	}
	RESULT=plato;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("RECETA",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // SECCIONRECETAS ::= RECETA N1 SECCIONRECETAS 
            {
              ArrayList<Plato> RESULT =null;
		int recleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int recright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Plato rec = (Plato)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int vrecleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vrecright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Plato> vrec = (ArrayList<Plato>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	vrec.add(rec);
	RESULT=vrec;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SECCIONRECETAS",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // SECCIONRECETAS ::= RECETA N1 
            {
              ArrayList<Plato> RESULT =null;
		int recleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int recright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Plato rec = (Plato)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	ArrayList<Plato> vrecetas = new ArrayList<Plato>();
	vrecetas.add(rec);
	RESULT=vrecetas;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SECCIONRECETAS",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // INGREDIENTE ::= id dospuntos numero medidaIngrediente cadena pcoma 
            {
              Ingrediente RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int canleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int canright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer can = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int medleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int medright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String med = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	Ingrediente ingrediente = new Ingrediente(id, nom.substring(1,nom.length()-2), can, EnumMedida.valueOf(med));
	RESULT=ingrediente;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("INGREDIENTE",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // LISTADOINGREDIENTES ::= INGREDIENTE LISTADOINGREDIENTES 
            {
              ArrayList<Ingrediente> RESULT =null;
		int ingleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int ingright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Ingrediente ing = (Ingrediente)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int vingleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vingright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Ingrediente> ving = (ArrayList<Ingrediente>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	ving.add(ing);
	RESULT=ving;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTADOINGREDIENTES",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // LISTADOINGREDIENTES ::= INGREDIENTE 
            {
              ArrayList<Ingrediente> RESULT =null;
		int ingleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ingright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Ingrediente ing = (Ingrediente)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	ArrayList<Ingrediente> vingredientes = new ArrayList<Ingrediente>();
	vingredientes.add(ing);
	RESULT=vingredientes;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTADOINGREDIENTES",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SECCIONINGREDIENTES ::= 
            {
              ArrayList<Ingrediente> RESULT =null;
		
	RESULT=new ArrayList<Ingrediente>();

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SECCIONINGREDIENTES",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SECCIONINGREDIENTES ::= ingredientes izqLlave LISTADOINGREDIENTES drchLlave 
            {
              ArrayList<Ingrediente> RESULT =null;
		int vingleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vingright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Ingrediente> ving = (ArrayList<Ingrediente>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	RESULT=ving;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SECCIONINGREDIENTES",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // PLATO ::= id dospuntos cadena pcoma 
            {
              Plato RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	Plato plato = new Plato(id, nom);
	RESULT=plato;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PLATO",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // LISTADOPLATOS ::= PLATO LISTADOPLATOS 
            {
              ArrayList<Plato> RESULT =null;
		int plaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int plaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Plato pla = (Plato)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int vplaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vplaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Plato> vpla = (ArrayList<Plato>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	vpla.add(pla);
	RESULT=vpla;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTADOPLATOS",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // LISTADOPLATOS ::= PLATO 
            {
              ArrayList<Plato> RESULT =null;
		int plaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int plaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Plato pla = (Plato)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	ArrayList<Plato> vplatos = new ArrayList<Plato>();
	vplatos.add(pla);
	RESULT=vplatos;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTADOPLATOS",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SECCIONPLATOS ::= platos izqLlave LISTADOPLATOS drchLlave 
            {
              ArrayList<Plato> RESULT =null;
		int vplaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vplaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Plato> vpla = (ArrayList<Plato>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	RESULT=vpla;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SECCIONPLATOS",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // N3 ::= 
            {
              Integer RESULT =null;
		
	RESULT=((Integer) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value)+4;;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("N3",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // N1 ::= 
            {
              Integer RESULT =null;
		
	RESULT=((Integer) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value)+2;;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("N1",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NINIT ::= 
            {
              Integer RESULT =null;
		
	RESULT=0;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NINIT",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // AUTOR ::= nickname id pcoma 
            {
              String RESULT =null;
		int autleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int autright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String aut = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	RESULT=aut;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("AUTOR",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // SECCIONMENU ::= menu id dospuntos cadena izqLlave AUTOR SECCIONPLATOS SECCIONINGREDIENTES NINIT SECCIONRECETAS drchLlave 
            {
              Menu RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int autleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int autright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String aut = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int vplaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int vplaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		ArrayList<Plato> vpla = (ArrayList<Plato>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int vingleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int vingright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<Ingrediente> ving = (ArrayList<Ingrediente>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int vpla2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vpla2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Plato> vpla2 = (ArrayList<Plato>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
	Menu menu = new Menu(id, nom, aut, vpla2, ving);
	RESULT=menu;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SECCIONMENU",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // PROGRAMA ::= SECCIONMENU PROGRAMA 
            {
              ArrayList<Menu> RESULT =null;
		int menleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int menright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Menu men = (Menu)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int vmenleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vmenright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Menu> vmen = (ArrayList<Menu>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	vmen.add(men);
	RESULT=vmen;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PROGRAMA",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // PROGRAMA ::= SECCIONMENU 
            {
              ArrayList<Menu> RESULT =null;
		int menleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int menright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Menu men = (Menu)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	ArrayList<Menu> vmenus = new ArrayList<Menu>();
	vmenus.add(men);
	RESULT=vmenus;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PROGRAMA",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // S ::= PROGRAMA 
            {
              Object RESULT =null;
		int vmenleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vmenright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Menu> vmen = (ArrayList<Menu>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
	for(Menu m : vmen) {
		System.out.println("Menu");
		System.out.println("ID: "+m.getID());
		System.out.println("Nombre: "+m.getNombre());
		System.out.println("Autor: "+m.getNickname());
		for(Ingrediente i : m.getIngredientesGlobales()) {
			System.out.println("Ingrediente global");
			System.out.println("ID: "+i.getID());
			System.out.println("Nombre: "+i.getNombre());
			System.out.println("Cantidad: "+i.getCantidad());
			System.out.println("Medida: "+i.getMedida());
			System.out.println(",");
		}
		for(Plato p : m.getPlatos()) {
			System.out.println("Plato");
			System.out.println("ID: "+p.getID());
			System.out.println("Nombre: "+p.getNombre());
			System.out.println("Tipo: "+p.getTipo());
			System.out.println("Comensales: "+p.getComensales());
			System.out.println("TCocinado: "+p.getTiempos().getTCocinado());
			System.out.println("MCocinado: "+p.getTiempos().getMCocinado());
			System.out.println("TPreparacion: "+p.getTiempos().getTPreparacion());
			System.out.println("MPreparacion: "+p.getTiempos().getMPreparacion());
			System.out.println("TTotal: "+p.getTiempos().getTTotal());
			System.out.println("MTotal: "+p.getTiempos().getMTotal());
			for(Ingrediente i : p.getIngredientes()) {
				System.out.println("Ingrediente");
				System.out.println("ID: "+i.getID());
				System.out.println("Nombre: "+i.getNombre());
				System.out.println("Cantidad: "+i.getCantidad());
				System.out.println("Medida: "+i.getMedida());
				System.out.println(",");
			}
			for(Paso pa : p.getPasos()) {
				System.out.println("Paso");
				System.out.println("Descripcion: "+pa.getDescripcion());
				System.out.println(",");
			}
			System.out.println(",");
		}
	}

              CUP$parser$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

