
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 16 18:12:44 CET 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menu = 17;
  public static final int cadena = 3;
  public static final int medidaIngrediente = 6;
  public static final int tipo = 23;
  public static final int nombreTipo = 5;
  public static final int coma = 12;
  public static final int tCocinado = 28;
  public static final int numero = 8;
  public static final int pcoma = 11;
  public static final int drchParent = 15;
  public static final int platos = 18;
  public static final int comensales = 21;
  public static final int medidaTiempo = 7;
  public static final int tPreparacion = 30;
  public static final int izqParent = 14;
  public static final int tTotal = 29;
  public static final int pasos = 22;
  public static final int drchLlave = 10;
  public static final int izqLlave = 9;
  public static final int EOF = 0;
  public static final int realizar = 26;
  public static final int invertir = 4;
  public static final int id = 2;
  public static final int error = 1;
  public static final int nickname = 16;
  public static final int ingredientes = 27;
  public static final int introducir = 20;
  public static final int sacar = 19;
  public static final int programar = 24;
  public static final int dospuntos = 13;
  public static final int plato = 25;
}

