
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 13 00:06:15 CET 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menu = 11;
  public static final int cadena = 4;
  public static final int tipo = 21;
  public static final int tiempo = 24;
  public static final int coma = 8;
  public static final int tCocinado = 26;
  public static final int pcoma = 7;
  public static final int drchParent = 10;
  public static final int platos = 13;
  public static final int comensales = 16;
  public static final int tPreparacion = 28;
  public static final int izqParent = 9;
  public static final int tTotal = 27;
  public static final int pasos = 17;
  public static final int drchLlave = 6;
  public static final int izqLlave = 5;
  public static final int EOF = 0;
  public static final int invertir = 23;
  public static final int realizar = 20;
  public static final int id = 3;
  public static final int medida = 22;
  public static final int error = 1;
  public static final int nickname = 12;
  public static final int ingredientes = 25;
  public static final int introducir = 15;
  public static final int sacar = 14;
  public static final int entero = 2;
  public static final int programar = 18;
  public static final int plato = 19;
}

