
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 12 12:10:10 CET 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menu = 11;
  public static final int cadena = 4;
  public static final int paso = 21;
  public static final int tipo = 16;
  public static final int tiempo = 26;
  public static final int coma = 8;
  public static final int tCocinado = 28;
  public static final int pcoma = 7;
  public static final int drchParent = 10;
  public static final int platos = 13;
  public static final int comensales = 17;
  public static final int tPreparacion = 30;
  public static final int izqParent = 9;
  public static final int tTotal = 29;
  public static final int pasos = 18;
  public static final int drchLlave = 6;
  public static final int izqLlave = 5;
  public static final int EOF = 0;
  public static final int invertir = 25;
  public static final int realizar = 22;
  public static final int id = 3;
  public static final int medida = 24;
  public static final int error = 1;
  public static final int nickname = 12;
  public static final int ingredientes = 27;
  public static final int introducir = 15;
  public static final int sacar = 14;
  public static final int enumTipo = 23;
  public static final int entero = 2;
  public static final int programar = 19;
  public static final int plato = 20;
}

