
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menu = 16;
  public static final int cadena = 3;
  public static final int medidaIngrediente = 4;
  public static final int tipo = 21;
  public static final int nombreTipo = 5;
  public static final int coma = 13;
  public static final int tCocinado = 23;
  public static final int numero = 8;
  public static final int pcoma = 14;
  public static final int drchParent = 12;
  public static final int platos = 18;
  public static final int comensales = 22;
  public static final int medidaTiempo = 6;
  public static final int tPreparacion = 24;
  public static final int izqParent = 11;
  public static final int pasos = 26;
  public static final int tTotal = 25;
  public static final int drchLlave = 10;
  public static final int izqLlave = 9;
  public static final int EOF = 0;
  public static final int realizar = 30;
  public static final int invertir = 7;
  public static final int id = 2;
  public static final int error = 1;
  public static final int nickname = 17;
  public static final int sacar = 29;
  public static final int introducir = 27;
  public static final int ingredientes = 19;
  public static final int programar = 28;
  public static final int dospuntos = 15;
  public static final int plato = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "cadena",
  "medidaIngrediente",
  "nombreTipo",
  "medidaTiempo",
  "invertir",
  "numero",
  "izqLlave",
  "drchLlave",
  "izqParent",
  "drchParent",
  "coma",
  "pcoma",
  "dospuntos",
  "menu",
  "nickname",
  "platos",
  "ingredientes",
  "plato",
  "tipo",
  "comensales",
  "tCocinado",
  "tPreparacion",
  "tTotal",
  "pasos",
  "introducir",
  "programar",
  "sacar",
  "realizar"
  };
}

